# new servive account secret token in default namespace will be created
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: gitlab-ci
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: gitlab-ci
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: gitlab-ci
    namespace: default
